# Generated by Django 5.2.4 on 2025-07-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_about_qualification_service_skill_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='about',
            name='completed_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='about',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='about',
            name='profession',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='about',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualification',
            name='type',
            field=models.CharField(choices=[('education', 'Education'), ('work', 'Work')], default='education', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='about',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
    ]
