# Generated by Django 5.2.4 on 2025-08-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_about_address_about_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='about',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='profession',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='diploma',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institution',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
